---
name: 'Perl critic'

on: [push, pull_request]

jobs:
  perl-critic-checks:
    runs-on: ubuntu-latest
    name: "Perlcritic"
    container:
      image: perl:5.38-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y libperl-critic-toomuchcode-perl
      - run: make test-critic
      - run: tools/perlcritic -v lib
